### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [odoomrp/odoomrp-wip#1041]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [ ] machine_purchase_asset
- [ ] procurement_mrp_no_confirm
- [ ] partner_control_fields_view
- [ ] purchase_order_allowed_product
- [ ] sale_order_allowed_product
- [ ] mrp_bom_through_attributes
- [ ] stock_move_purchase_price
- [ ] product_last_mrp_info
- [ ] stock_packaging_info
- [ ] quality_control_mrp
- [ ] procurement_plan_mrp
- [ ] procurement_sale_forecast
- [ ] mrp_production_sale_info
- [ ] sale_order_allowed_product_template
- [ ] crm_claim_corrective
- [ ] mrp_wizard_filter_task
- [ ] stock_picking_wave_package_info
- [ ] product_attribute_value_image
- [ ] procurement_orderpoint_no_confirm
- [ ] machine_manager
- [ ] sale_product_variants
- [ ] purchase_order_last_prices
- [ ] sale_packaging_info_product_variants
- [ ] mrp_machine_relation
- [ ] sale_order_last_prices
- [ ] product_template_reassign
- [ ] purchase_product_variants
- [ ] product_secondary_unit
- [ ] procurement_purchase_no_grouping
- [ ] mrp_production_add_middle_stuff_lot
- [ ] mrp_product_variants_operations
- [ ] sale_order_recalculate_prices_variants
- [ ] mrp_operations_project
- [ ] mrp_configurable_timing
- [ ] mrp_production_traceability
- [ ] purchase_product_price_history
- [ ] mrp_production_project_estimated_cost
- [ ] mrp_packaging
- [ ] purchase_secondary_unit
- [ ] purchase_product_variants_types
- [ ] mrp_bom_by_percentage
- [ ] mrp_bom_sale_pack
- [ ] stock_lock_lot
- [ ] quality_control_samples
- [ ] mrp_production_simulated_capacity
- [ ] mrp_bom_component_change
- [ ] purchase_landed_cost
- [ ] account_treasury_forecast_cashflow_banking
- [ ] product_pricelist_import
- [ ] mrp_production_editable_scheduled_products
- [ ] purchase_order_allowed_product_template
- [ ] purchase_mrp_project_link
- [ ] machine_purchase
- [ ] quality_control_hr
- [ ] sale_mrp_project_link
- [ ] stock_purchase_unit
- [ ] sale_promotion_gift
- [ ] crm_claim_links
- [ ] mrp_lot_reserve
- [ ] sale_order_line_dates
- [ ] quality_control_sale_stock
- [ ] machine_manager_preventive
- [ ] mrp_repair_full_editable
- [ ] sale_order_line_view
- [ ] quality_control_between_dates
- [ ] mrp_product_variants_configurable_timing
- [ ] mrp_product_variants
- [ ] purchase_pricelist_rules
- [ ] mrp_packaging_quant_manual_assign
- [ ] purchase_homologation
- [ ] quality_control_claim
- [ ] product_variant_default_code
- [ ] stock_invoicing_type
- [ ] mrp_product_variants_types
- [ ] stock_quant_packages_moving_wizard
- [ ] sale_order_recalculate_prices
- [ ] sale_delivery_date
- [ ] account_treasury_forecast_cashflow
- [ ] sale_order_taxes
- [ ] warning_log
- [ ] quality_control_stock
- [ ] mrp_production_add_middle_stuff
- [ ] quality_control_force_valid
- [ ] mrp_packaging_project_link
- [ ] mrp_production_capacity
- [ ] stock_move_check_availability
- [ ] product_packaging_through_attributes
- [ ] purchase_requisition_display_order_line
- [ ] mrp_stock_location_route_fix
- [ ] product_variant_cost
- [ ] partner_risk_insurance
- [ ] procurement_plan
- [ ] sale_product_variants_types
- [ ] product_attribute_types_views
- [ ] stock_quant_merge
- [ ] mrp_bom_catch_product_code
- [ ] quality_control_tolerance
- [ ] account_treasury_forecast_banking
- [ ] sale_proforma_report
- [ ] stock_quant_manual_assign_without_lock_lot
- [ ] product_purchase_warrant
- [ ] mrp_project_link
- [ ] quality_control
- [ ] product_price_history
- [ ] procurement_service
- [ ] product_variants_types
- [ ] base_partner_references
- [ ] stock_picking_package_info
- [ ] product_attribute_types
- [ ] account_treasury_forecast
- [ ] mrp_byproduct_operations
- [ ] procurement_plan_project
- [ ] sale_uos_price
- [ ] mrp_operations_start_without_material
- [ ] sale_pricelist_rules
- [ ] sale_documents_comments
- [ ] stock_inventory_import
- [ ] mrp_repair_analytic
- [ ] delivery_multi_expense
- [ ] mrp_subcontracting
- [ ] purchase_requisition_full_bid_order_generator
- [ ] mrp_repair_stock_picking_out
- [ ] quality_control_mrp_operations
- [ ] mrp_production_add_middle_stuff_operations
- [ ] procurement_purchase_forecast
- [ ] product_suppliers_from_category
- [ ] mrp_production_real_costs
- [ ] stock_picking_wave_delivery
- [ ] stock_picking_wave_management
- [ ] mrp_operations_traceability
- [ ] mrp_production_manual_close
- [ ] mrp_operations_time_control
- [ ] mrp_final_product_lot
- [ ] product_variants_no_automatic_creation
- [ ] mrp_lock_lot
- [ ] product_pricelist_rules
- [ ] mrp_operations_extension
- [ ] stock_picking_taxes
- [ ] purchase_packaging_info
- [ ] sale_packaging_info
- [ ] product_attribute_views
