### ISSUE TITLE
[2014-12-12] To test

### ISSUE THREAD

**Issue by oihane** [odoomrp/odoomrp-wip#441]
Cosas para probar
- [x] que el proceso de fabricación con variantes funciona como debe ya que se ha dividido en dos el modulo `mrp_product_variants` de manera que se desvincula del módulo `mrp_operations_extension` #417

**Comment by oihane** [comment]
@agaldona @Daniel-CA @alfredoavanzosc @mikelarre 

He creado este issue para que pongamos aquellas cosas que queramos que pruebe @anajuaristi este fin de semana en el server de la oficina.

Para poner los checks hay que escribir `- [ ]` al inicio de la línea. De esa manera ella puede marcar los que haya validado :wink:

**Comment by Daniel-CA** [comment]
- [x] `mrp_production_add_middle_stuff`: Yo no se si el bug que reportó se ha arreglado o sigue igual, por que no estoy seguro de que fuera error de este módulo. #391 **mergeado**

**Comment by mikelarre** [comment]
- [ ] `alm*_checks` Issue 181 de ALM
- [x] `product_expiry_ext`: colorea quants en base al lote que esta relacionado #438

**Comment by agaldona** [comment]
- [ ] `di*_mrp_labelling_control`: Etiquetado por países
- [x] `procurement_sale_forecast`: MPS - la parte de ventas y abastecimientos #439 
- [x] `procurement_purchase_forecast`: MPS - asistente de carga de líneas de compra #439
